# Generated by Django 5.0.6 on 2024-07-01 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_expense_invoice_amount_paid_invoice_balance_due_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='expense',
            name='receipt_image',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='balance_due',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='template',
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='INV-0001', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
